import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {

  const url = "https://mflixbackredecanais.herokuapp.com/data"
  const pull = await fetch(url)
  const pullJson = await pull.json()
  const data = pullJson.filter(x=> x.poster_path !== null)
  console.log(data)

  return {
    props: {
      data,
    },
    revalidate: 24*60*60, // In seconds
  }
}
export default function Home({data}) {
  const [useData,setData] = useState(false)
  const [baseUrl] = useState("https://redecanais.to")
  const [imgUrl] = useState('https://image.tmdb.org/t/p/w300')
  useEffect(()=>{
    setData(data)
  },[data])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cards}>
          {useData && useData.map((item,i)=>{
              console.log(item.poster_path)
              return(            
                    <div key={item.title + i} className={styles.card}>
                      <Link href={baseUrl+item.url}>
                        <a >                         
                          <Image   
                          className={styles.image}                         
                            src={imgUrl+item.poster_path}
                            width={193}
                            height={300}
                            layout="intrinsic"
                            alt={item.title}
                          />
                        </a>
                      </Link>                    
                    </div>
              )
            })}
        </div>        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
